### ISSUE TITLE
'Account' object has no attribute 'operations'

### ISSUE THREAD

**Issue by Lperreau** [dmachard/creditagricole-particuliers#2]
Please, replace: 

operations = main_account.**operations(count=30)**
for op in operations:
    print(op)

by 

operations = main_account.**get_operations(count=30)**
for op in operations:
    print(op)

Thank you! :)

**Comment by dmachard** [comment]
Hi, feel free to submit a pull request to fix this typo error. Thanks for your support and contribution.
